# Generated by Django 5.0.1 on 2024-09-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterField(
            model_name='shippinguser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='shippinguser_group', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='shippinguser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='shippinguser_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
