# Generated by Django 5.0.1 on 2024-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default='7905965119', editable=False, max_length=10, unique=True),
        ),
    ]
