# Generated by Django 5.0.1 on 2024-09-05 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_shipment_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.CharField(default='5564938091', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shipment')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_shipment_status', to='api.shippinguser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shippinguser')),
            ],
        ),
    ]
